name: encoder-addition-dev

channels:
  - pytorch
  
dependencies:
  - pytorch=2.4.0
  - numpy=1.26.4
  - python=3.12.2
  - scikit-learn=1.4.0
  - pip=24.0
  - pip:
    - tqdm==4.66.1
    - wandb==0.17.5
    - transformers==4.42.3
    - numba==0.60.0